### ISSUE TITLE
List i2c addresses for micro:bit variants

### ISSUE THREAD

**Issue by microbit-mark** [Gadgetoid/microbit.pinout.xyz#1]
@Gadgetoid we'd like to link to this resource on tech.microbit.org. Could you update info on
https://github.com/Gadgetoid/microbit.pinout.xyz/blob/master/pin/p19.md
https://github.com/Gadgetoid/microbit.pinout.xyz/blob/master/pin/p20.md

with current information from
https://tech.microbit.org/hardware/i2c/#table-of-addresses-used

suggest something like:
"Two devices are connected to the micro:bit's I²C bus internally; the Accelerometer and Magnetometer. The I²C address used is [dependent on the variant of the device you have](https://tech.microbit.org/hardware/i2c/#table-of-addresses-used). You cannot connect an external device that uses either of these addresses."

**Comment by tguneysu** [comment]
Following error noted on pin 11 description:
P11 (the other being **P11)** is one of the two pins wired directly to the micro:bits onboard A and B push buttons.
Should be P5.

**Comment by JoshuaLowe1002** [comment]
I’ll add these fixes into #3 before it is merged
